// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: wallet.proto

package cn.hsiangsun.wallet.rpc.wallet;

public interface AddressResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:wallet.AddressResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string address = 1;</code>
   */
  java.lang.String getAddress();
  /**
   * <code>string address = 1;</code>
   */
  com.google.protobuf.ByteString
      getAddressBytes();
}
