// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: wallet.proto

package cn.hsiangsun.wallet.rpc.wallet;

public interface AddressRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:wallet.AddressRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string secret = 1;</code>
   */
  java.lang.String getSecret();
  /**
   * <code>string secret = 1;</code>
   */
  com.google.protobuf.ByteString
      getSecretBytes();

  /**
   * <code>string uid = 2;</code>
   */
  java.lang.String getUid();
  /**
   * <code>string uid = 2;</code>
   */
  com.google.protobuf.ByteString
      getUidBytes();
}
