// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: wallet.proto

package cn.hsiangsun.wallet.rpc.wallet;

public final class WalletProto {
  private WalletProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_wallet_AddressRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_wallet_AddressRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_wallet_AddressResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_wallet_AddressResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014wallet.proto\022\006wallet\"-\n\016AddressRequest" +
      "\022\016\n\006secret\030\001 \001(\t\022\013\n\003uid\030\002 \001(\t\"\"\n\017Address" +
      "Response\022\017\n\007address\030\001 \001(\t2O\n\007Address\022D\n\017" +
      "GenerateAddress\022\026.wallet.AddressRequest\032" +
      "\027.wallet.AddressResponse\"\000B=\n\036cn.hsiangs" +
      "un.wallet.rpc.walletB\013WalletProtoP\001Z\007/wa" +
      "llet\242\002\002HLb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_wallet_AddressRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_wallet_AddressRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_wallet_AddressRequest_descriptor,
        new java.lang.String[] { "Secret", "Uid", });
    internal_static_wallet_AddressResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_wallet_AddressResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_wallet_AddressResponse_descriptor,
        new java.lang.String[] { "Address", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
